name: salle_maps
description: Final project of the Flutter Course of our university.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  toggle_switch: "^0.1.8"
  font_awesome_flutter: ^8.10.0
  google_maps_flutter: ^1.0.6
  provider: ^4.3.2+3

  # Firebase
  firebase_core: ^0.5.3
    # Auth
  firebase_auth: ^0.18.4
  google_sign_in: ^4.5.6

  cupertino_icons: ^1.0.0

  # Color picker
  flutter_colorpicker: ^0.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Regular.ttf
        - asset: fonts/Dosis-ExtraLight.ttf
        - asset: fonts/Dosis-Light.ttf
        - asset: fonts/Dosis-Medium.ttf
        - asset: fonts/Dosis-SemiBold.ttf
          weight: 600
        - asset: fonts/Dosis-Bold.ttf
          weight: 700
        - asset: fonts/Dosis-ExtraBold.ttf
          weight: 800
